# AdventureWorks Analytics Project — Data Loading Phase

## Objective
The goal of this phase is to load all raw AdventureWorks datasets into Python using Pandas and perform an initial inspection of the data structure.

This phase serves as the foundation for the entire analytics pipeline and helps in understanding:
- dataset structure
- column information
- datatypes
- row counts
- data quality
- table relationships

---

# Datasets Used

The following raw datasets are loaded from the `01_data/01_raw/` directory:

| Dataset | Purpose |
|---|---|
| sales_order_header.csv | Sales transaction headers |
| sales_order_detail.csv | Product-level transaction details |
| customer.csv | Customer mapping information |
| product.csv | Product master data |
| product_category.csv | Product category hierarchy |
| product_subcategory.csv | Product subcategory hierarchy |
| sales_territory.csv | Regional sales information |
| sales_person.csv | Salesperson performance data |
| person.csv | Customer/person information |
| address.csv | Geographic location details |
| purchase_order_header.csv | Procurement and purchasing data |

---

# Goals of This Notebook

This notebook focuses on:

1. Loading raw CSV files into Pandas DataFrames
2. Inspecting dataset shapes and columns
3. Validating datatypes
4. Identifying missing values
5. Understanding table granularity
6. Preparing datasets for cleaning and feature engineering

---

# Expected Outcome

At the end of this phase:
- all raw datasets will be successfully loaded
- dataset structures will be validated
- data quality issues will be identified
- the project will be ready for Exploratory Data Analysis (EDA) and data cleaning

---

# Tools & Libraries

This phase primarily uses:
- Python
- Pandas
- NumPy

The processed datasets generated later will be used for:
- SQL analytics
- Tableau dashboards
- Advanced Python analysis
- Business KPI reporting

In [1]:
# Importing all Libraries

import pandas as pd 
import numpy as np 

#Load raw Datasets

sales_order_header = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/sales_order_header.csv')
sales_order_detail = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/sales_order_detail.csv')
customer = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/customer.csv')
product = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/product.csv')
product_category = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/product_category.csv')
product_subcategory = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/product_subcategory.csv')
sales_territory = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/sales_territory.csv')
sales_person = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/sales_person.csv')
person = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/person.csv')
address = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/person_address.csv')
purchase_order_header = pd.read_csv('/Users/yashmalviya/AdventureWorks-Docker/01_data/01_raw/purchase_order_header.csv')

## Verifying successful loading 

datasets = {
    "sales_order_header": sales_order_header,
    "sales_order_detail": sales_order_detail,
    "customer": customer,
    "product": product,
    "product_category": product_category,
    "product_subcategory": product_subcategory,
    "sales_territory": sales_territory,
    "sales_person": sales_person,
    "person": person,
    "address": address,
    "purchase_order_header": purchase_order_header
}

# Print Dataset Shapes
for name, df in datasets.items():
    print(f"{name}: {df.shape}")

sales_order_header: (31465, 26)
sales_order_detail: (121317, 11)
customer: (19820, 7)
product: (504, 25)
product_category: (4, 4)
product_subcategory: (37, 5)
sales_territory: (10, 10)
sales_person: (17, 9)
person: (19972, 13)
address: (19614, 9)
purchase_order_header: (4012, 13)

# Dataset Inspection & Initial Exploration

## Objective
After successfully loading the raw datasets, the next step is to perform an initial inspection of the data.

This phase helps in understanding:
- dataset dimensions
- column structure
- datatypes
- missing values
- sample records
- overall data quality

Understanding the raw data before cleaning is an important step in every analytics workflow.

---

# Key Goals

This section focuses on:

1. Viewing dataset shapes
2. Inspecting column names
3. Checking datatypes
4. Identifying missing values
5. Previewing sample records
6. Understanding table granularity

---

# Why This Step Matters

Exploratory inspection helps analysts:
- detect data quality issues early
- identify incorrect datatypes
- understand relationships between tables
- prepare for cleaning and feature engineering

This step is critical before:
- data transformation
- business analysis
- dashboard development
- KPI calculations

---

# Expected Outcome

At the end of this phase:
- dataset structures will be fully understood
- null values and inconsistencies will be identified
- important business columns will be recognized
- the project will be ready for data cleaning

In [2]:
# Dataset Inspection

for name, df in datasets.items():

    print("\n" + "=" * 60)
    print(f"DATASET: {name.upper()}")
    print("=" * 60)

    # Shape
    print(f"\nShape: {df.shape}")

    # Column Names
    print("\nColumns:")
    print(df.columns.tolist())

    # Data Types
    print("\nData Types:")
    print(df.dtypes)

    # Missing Values
    print("\nMissing Values:")
    print(df.isnull().sum())

    # Sample Records
    print("\nFirst 5 Rows:")
    display(df.head())

============================================================
DATASET: SALES_ORDER_HEADER
============================================================

Shape: (31465, 26)

Columns:
['SalesOrderID', 'RevisionNumber', 'OrderDate', 'DueDate', 'ShipDate', 'Status', 'OnlineOrderFlag', 'SalesOrderNumber', 'PurchaseOrderNumber', 'AccountNumber', 'CustomerID', 'SalesPersonID', 'TerritoryID', 'BillToAddressID', 'ShipToAddressID', 'ShipMethodID', 'CreditCardID', 'CreditCardApprovalCode', 'CurrencyRateID', 'SubTotal', 'TaxAmt', 'Freight', 'TotalDue', 'Comment', 'rowguid', 'ModifiedDate']

Data Types:
SalesOrderID                int64
RevisionNumber              int64
OrderDate                     str
DueDate                       str
ShipDate                      str
Status                      int64
OnlineOrderFlag             int64
SalesOrderNumber              str
PurchaseOrderNumber           str
AccountNumber                 str
CustomerID                  int64
SalesPersonID             float64
TerritoryID                 int64
BillToAddressID             int64
ShipToAddressID             int64
ShipMethodID                int64
CreditCardID              float64
CreditCardApprovalCode        str
CurrencyRateID            float64
SubTotal                  float64
TaxAmt                    float64
Freight                   float64
TotalDue                  float64
Comment                   float64
rowguid                       str
ModifiedDate                  str
dtype: object

Missing Values:
SalesOrderID                  0
RevisionNumber                0
OrderDate                     0
DueDate                       0
ShipDate                      0
Status                        0
OnlineOrderFlag               0
SalesOrderNumber              0
PurchaseOrderNumber       27659
AccountNumber                 0
CustomerID                    0
SalesPersonID             27659
TerritoryID                   0
BillToAddressID               0
ShipToAddressID               0
ShipMethodID                  0
CreditCardID               1131
CreditCardApprovalCode     1131
CurrencyRateID            17489
SubTotal                      0
TaxAmt                        0
Freight                       0
TotalDue                      0
Comment                   31465
rowguid                       0
ModifiedDate                  0
dtype: int64

First 5 Rows:

,SalesOrderID,RevisionNumber,OrderDate,DueDate,ShipDate,Status,OnlineOrderFlag,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,...,CreditCardID,CreditCardApprovalCode,CurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment,rowguid,ModifiedDate
0,43659,8,2011-05-31 00:00:00.000,2011-06-12 00:00:00.000,2011-06-07 00:00:00.000,5,0,SO43659,PO522145787,10-4020-000676,...,16281.0,105041Vi84182,NaN,20565.6206,1971.5149,616.0984,23153.2339,NaN,79b65321-39ca-4115-9cba-8fe0903e12e6,2011-06-07 00:00:00.000
1,43660,8,2011-05-31 00:00:00.000,2011-06-12 00:00:00.000,2011-06-07 00:00:00.000,5,0,SO43660,PO18850127500,10-4020-000117,...,5618.0,115213Vi29411,NaN,1294.2529,124.2483,38.8276,1457.3288,NaN,738dc42d-d03b-48a1-9822-f95a67ea7389,2011-06-07 00:00:00.000
2,43661,8,2011-05-31 00:00:00.000,2011-06-12 00:00:00.000,2011-06-07 00:00:00.000,5,0,SO43661,PO18473189620,10-4020-000442,...,1346.0,85274Vi6854,4.0,32726.4786,3153.7696,985.5530,36865.8012,NaN,d91b9131-18a4-4a11-bc3a-90b6f53e9d74,2011-06-07 00:00:00.000
3,43662,8,2011-05-31 00:00:00.000,2011-06-12 00:00:00.000,2011-06-07 00:00:00.000,5,0,SO43662,PO18444174044,10-4020-000227,...,10456.0,125295Vi53935,4.0,28832.5289,2775.1646,867.2389,32474.9324,NaN,4a1ecfc0-cc3a-4740-b028-1c50bb48711c,2011-06-07 00:00:00.000
4,43663,8,2011-05-31 00:00:00.000,2011-06-12 00:00:00.000,2011-06-07 00:00:00.000,5,0,SO43663,PO18009186470,10-4020-000510,...,4322.0,45303Vi22691,NaN,419.4589,40.2681,12.5838,472.3108,NaN,9b1e7a40-6ae0-4ad3-811c-a64951857c4b,2011-06-07 00:00:00.000

============================================================
DATASET: SALES_ORDER_DETAIL
============================================================

Shape: (121317, 11)

Columns:
['SalesOrderID', 'SalesOrderDetailID', 'CarrierTrackingNumber', 'OrderQty', 'ProductID', 'SpecialOfferID', 'UnitPrice', 'UnitPriceDiscount', 'LineTotal', 'rowguid', 'ModifiedDate']

Data Types:
SalesOrderID               int64
SalesOrderDetailID         int64
CarrierTrackingNumber        str
OrderQty                   int64
ProductID                  int64
SpecialOfferID             int64
UnitPrice                float64
UnitPriceDiscount        float64
LineTotal                float64
rowguid                      str
ModifiedDate                 str
dtype: object

Missing Values:
SalesOrderID                 0
SalesOrderDetailID           0
CarrierTrackingNumber    60398
OrderQty                     0
ProductID                    0
SpecialOfferID               0
UnitPrice                    0
UnitPriceDiscount            0
LineTotal                    0
rowguid                      0
ModifiedDate                 0
dtype: int64

First 5 Rows:

,SalesOrderID,SalesOrderDetailID,CarrierTrackingNumber,OrderQty,ProductID,SpecialOfferID,UnitPrice,UnitPriceDiscount,LineTotal,rowguid,ModifiedDate
0,43659,1,4911-403C-98,1,776,1,2024.994,0.0,2024.994,b207c96d-d9e6-402b-8470-2cc176c42283,2011-05-31 00:00:00.000
1,43659,2,4911-403C-98,3,777,1,2024.994,0.0,6074.982,7abb600d-1e77-41be-9fe5-b9142cfc08fa,2011-05-31 00:00:00.000
2,43659,3,4911-403C-98,1,778,1,2024.994,0.0,2024.994,475cf8c6-49f6-486e-b0ad-afc6a50cdd2f,2011-05-31 00:00:00.000
3,43659,4,4911-403C-98,1,771,1,2039.994,0.0,2039.994,04c4de91-5815-45d6-8670-f462719fbce3,2011-05-31 00:00:00.000
4,43659,5,4911-403C-98,1,772,1,2039.994,0.0,2039.994,5a74c7d2-e641-438e-a7ac-37bf23280301,2011-05-31 00:00:00.000

============================================================
DATASET: CUSTOMER
============================================================

Shape: (19820, 7)

Columns:
['CustomerID', 'PersonID', 'StoreID', 'TerritoryID', 'AccountNumber', 'rowguid', 'ModifiedDate']

Data Types:
CustomerID         int64
PersonID         float64
StoreID          float64
TerritoryID        int64
AccountNumber        str
rowguid              str
ModifiedDate         str
dtype: object

Missing Values:
CustomerID           0
PersonID           701
StoreID          18484
TerritoryID          0
AccountNumber        0
rowguid              0
ModifiedDate         0
dtype: int64

First 5 Rows:

,CustomerID,PersonID,StoreID,TerritoryID,AccountNumber,rowguid,ModifiedDate
0,1,NaN,934.0,1,AW00000001,3f5ae95e-b87d-4aed-95b4-c3797afcb74f,2014-09-12 11:15:07.263
1,2,NaN,1028.0,1,AW00000002,e552f657-a9af-4a7d-a645-c429d6e02491,2014-09-12 11:15:07.263
2,3,NaN,642.0,4,AW00000003,130774b1-db21-4ef3-98c8-c104bcd6ed6d,2014-09-12 11:15:07.263
3,4,NaN,932.0,4,AW00000004,ff862851-1daa-4044-be7c-3e85583c054d,2014-09-12 11:15:07.263
4,5,NaN,1026.0,4,AW00000005,83905bdc-6f5e-4f71-b162-c98da069f38a,2014-09-12 11:15:07.263

============================================================
DATASET: PRODUCT
============================================================

Shape: (504, 25)

Columns:
['ProductID', 'Name', 'ProductNumber', 'MakeFlag', 'FinishedGoodsFlag', 'Color', 'SafetyStockLevel', 'ReorderPoint', 'StandardCost', 'ListPrice', 'Size', 'SizeUnitMeasureCode', 'WeightUnitMeasureCode', 'Weight', 'DaysToManufacture', 'ProductLine', 'Class', 'Style', 'ProductSubcategoryID', 'ProductModelID', 'SellStartDate', 'SellEndDate', 'DiscontinuedDate', 'rowguid', 'ModifiedDate']

Data Types:
ProductID                  int64
Name                         str
ProductNumber                str
MakeFlag                   int64
FinishedGoodsFlag          int64
Color                        str
SafetyStockLevel           int64
ReorderPoint               int64
StandardCost             float64
ListPrice                float64
Size                         str
SizeUnitMeasureCode          str
WeightUnitMeasureCode        str
Weight                   float64
DaysToManufacture          int64
ProductLine                  str
Class                        str
Style                        str
ProductSubcategoryID     float64
ProductModelID           float64
SellStartDate                str
SellEndDate                  str
DiscontinuedDate         float64
rowguid                      str
ModifiedDate                 str
dtype: object

Missing Values:
ProductID                  0
Name                       0
ProductNumber              0
MakeFlag                   0
FinishedGoodsFlag          0
Color                    248
SafetyStockLevel           0
ReorderPoint               0
StandardCost               0
ListPrice                  0
Size                     293
SizeUnitMeasureCode      328
WeightUnitMeasureCode    299
Weight                   299
DaysToManufacture          0
ProductLine              226
Class                    257
Style                    293
ProductSubcategoryID     209
ProductModelID           209
SellStartDate              0
SellEndDate              406
DiscontinuedDate         504
rowguid                    0
ModifiedDate               0
dtype: int64

First 5 Rows:

,ProductID,Name,ProductNumber,MakeFlag,FinishedGoodsFlag,Color,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,...,ProductLine,Class,Style,ProductSubcategoryID,ProductModelID,SellStartDate,SellEndDate,DiscontinuedDate,rowguid,ModifiedDate
0,1,Adjustable Race,AR-5381,0,0,NaN,1000,750,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN,NaN,694215b7-08f7-4c0d-acb1-d734ba44c0c8,2014-02-08 10:01:36.827
1,2,Bearing Ball,BA-8327,0,0,NaN,1000,750,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN,NaN,58ae3c20-4f3a-4749-a7d4-d568806cc537,2014-02-08 10:01:36.827
2,3,BB Ball Bearing,BE-2349,1,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN,NaN,9c21aed2-5bfa-4f18-bcb8-f11638dc2e4e,2014-02-08 10:01:36.827
3,4,Headset Ball Bearings,BE-2908,0,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN,NaN,ecfed6cb-51ff-49b5-b06c-7d8ac834db8b,2014-02-08 10:01:36.827
4,316,Blade,BL-2036,1,0,NaN,800,600,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,2008-04-30 00:00:00.000,NaN,NaN,e73e9750-603b-4131-89f5-3dd15ed5ff80,2014-02-08 10:01:36.827

============================================================
DATASET: PRODUCT_CATEGORY
============================================================

Shape: (4, 4)

Columns:
['ProductCategoryID', 'Name', 'rowguid', 'ModifiedDate']

Data Types:
ProductCategoryID    int64
Name                   str
rowguid                str
ModifiedDate           str
dtype: object

Missing Values:
ProductCategoryID    0
Name                 0
rowguid              0
ModifiedDate         0
dtype: int64

First 5 Rows:

,ProductCategoryID,Name,rowguid,ModifiedDate
0,1,Bikes,cfbda25c-df71-47a7-b81b-64ee161aa37c,2008-04-30 00:00:00.000
1,2,Components,c657828d-d808-4aba-91a3-af2ce02300e9,2008-04-30 00:00:00.000
2,3,Clothing,10a7c342-ca82-48d4-8a38-46a2eb089b74,2008-04-30 00:00:00.000
3,4,Accessories,2be3be36-d9a2-4eee-b593-ed895d97c2a6,2008-04-30 00:00:00.000

============================================================
DATASET: PRODUCT_SUBCATEGORY
============================================================

Shape: (37, 5)

Columns:
['ProductSubcategoryID', 'ProductCategoryID', 'Name', 'rowguid', 'ModifiedDate']

Data Types:
ProductSubcategoryID    int64
ProductCategoryID       int64
Name                      str
rowguid                   str
ModifiedDate              str
dtype: object

Missing Values:
ProductSubcategoryID    0
ProductCategoryID       0
Name                    0
rowguid                 0
ModifiedDate            0
dtype: int64

First 5 Rows:

,ProductSubcategoryID,ProductCategoryID,Name,rowguid,ModifiedDate
0,1,1,Mountain Bikes,2d364ade-264a-433c-b092-4fcbf3804e01,2008-04-30 00:00:00.000
1,2,1,Road Bikes,000310c0-bcc8-42c4-b0c3-45ae611af06b,2008-04-30 00:00:00.000
2,3,1,Touring Bikes,02c5061d-ecdc-4274-b5f1-e91d76bc3f37,2008-04-30 00:00:00.000
3,4,2,Handlebars,3ef2c725-7135-4c85-9ae6-ae9a3bdd9283,2008-04-30 00:00:00.000
4,5,2,Bottom Brackets,a9e54089-8a1e-4cf5-8646-e3801f685934,2008-04-30 00:00:00.000

============================================================
DATASET: SALES_TERRITORY
============================================================

Shape: (10, 10)

Columns:
['TerritoryID', 'Name', 'CountryRegionCode', 'Group', 'SalesYTD', 'SalesLastYear', 'CostYTD', 'CostLastYear', 'rowguid', 'ModifiedDate']

Data Types:
TerritoryID            int64
Name                     str
CountryRegionCode        str
Group                    str
SalesYTD             float64
SalesLastYear        float64
CostYTD              float64
CostLastYear         float64
rowguid                  str
ModifiedDate             str
dtype: object

Missing Values:
TerritoryID          0
Name                 0
CountryRegionCode    0
Group                0
SalesYTD             0
SalesLastYear        0
CostYTD              0
CostLastYear         0
rowguid              0
ModifiedDate         0
dtype: int64

First 5 Rows:

,TerritoryID,Name,CountryRegionCode,Group,SalesYTD,SalesLastYear,CostYTD,CostLastYear,rowguid,ModifiedDate
0,1,Northwest,US,North America,7.887187e+06,3.298694e+06,0.0,0.0,43689a10-e30b-497f-b0de-11de20267ff7,2008-04-30 00:00:00.000
1,2,Northeast,US,North America,2.402177e+06,3.607149e+06,0.0,0.0,00fb7309-96cc-49e2-8363-0a1ba72486f2,2008-04-30 00:00:00.000
2,3,Central,US,North America,3.072175e+06,3.205014e+06,0.0,0.0,df6e7fd8-1a8d-468c-b103-ed8addb452c1,2008-04-30 00:00:00.000
3,4,Southwest,US,North America,1.051085e+07,5.366576e+06,0.0,0.0,dc3e9ea0-7950-4431-9428-99dbcbc33865,2008-04-30 00:00:00.000
4,5,Southeast,US,North America,2.538667e+06,3.925071e+06,0.0,0.0,6dc4165a-5e4c-42d2-809d-4344e0ac75e7,2008-04-30 00:00:00.000

============================================================
DATASET: SALES_PERSON
============================================================

Shape: (17, 9)

Columns:
['BusinessEntityID', 'TerritoryID', 'SalesQuota', 'Bonus', 'CommissionPct', 'SalesYTD', 'SalesLastYear', 'rowguid', 'ModifiedDate']

Data Types:
BusinessEntityID      int64
TerritoryID         float64
SalesQuota          float64
Bonus               float64
CommissionPct       float64
SalesYTD            float64
SalesLastYear       float64
rowguid                 str
ModifiedDate            str
dtype: object

Missing Values:
BusinessEntityID    0
TerritoryID         3
SalesQuota          3
Bonus               0
CommissionPct       0
SalesYTD            0
SalesLastYear       0
rowguid             0
ModifiedDate        0
dtype: int64

First 5 Rows:

,BusinessEntityID,TerritoryID,SalesQuota,Bonus,CommissionPct,SalesYTD,SalesLastYear,rowguid,ModifiedDate
0,274,NaN,NaN,0.0,0.000,5.596976e+05,0.000000e+00,48754992-9ee0-4c0e-8c94-9451604e3e02,2010-12-28 00:00:00.000
1,275,2.0,300000.0,4100.0,0.012,3.763178e+06,1.750406e+06,1e0a7274-3064-4f58-88ee-4c6586c87169,2011-05-24 00:00:00.000
2,276,4.0,250000.0,2000.0,0.015,4.251369e+06,1.439156e+06,4dd9eee4-8e81-4f8c-af97-683394c1f7c0,2011-05-24 00:00:00.000
3,277,3.0,250000.0,2500.0,0.015,3.189418e+06,1.997186e+06,39012928-bfec-4242-874d-423162c3f567,2011-05-24 00:00:00.000
4,278,6.0,250000.0,500.0,0.010,1.453719e+06,1.620277e+06,7a0ae1ab-b283-40f9-91d1-167abf06d720,2011-05-24 00:00:00.000

============================================================
DATASET: PERSON
============================================================

Shape: (19972, 13)

Columns:
['BusinessEntityID', 'PersonType', 'NameStyle', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix', 'EmailPromotion', 'AdditionalContactInfo', 'Demographics', 'rowguid', 'ModifiedDate']

Data Types:
BusinessEntityID         int64
PersonType                 str
NameStyle                int64
Title                      str
FirstName                  str
MiddleName                 str
LastName                   str
Suffix                     str
EmailPromotion           int64
AdditionalContactInfo      str
Demographics               str
rowguid                    str
ModifiedDate               str
dtype: object

Missing Values:
BusinessEntityID             0
PersonType                   0
NameStyle                    0
Title                    18963
FirstName                    0
MiddleName                8499
LastName                     0
Suffix                   19919
EmailPromotion               0
AdditionalContactInfo    19962
Demographics                 0
rowguid                      0
ModifiedDate                 0
dtype: int64

First 5 Rows:

,BusinessEntityID,PersonType,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,EmailPromotion,AdditionalContactInfo,Demographics,rowguid,ModifiedDate
0,1,EM,0,NaN,Ken,J,Sánchez,NaN,0,NaN,"<IndividualSurvey xmlns=""http://schemas.micros...",92c4279f-1207-48a3-8448-4636514eb7e2,2009-01-07 00:00:00.000
1,2,EM,0,NaN,Terri,Lee,Duffy,NaN,1,NaN,"<IndividualSurvey xmlns=""http://schemas.micros...",d8763459-8aa8-47cc-aff7-c9079af79033,2008-01-24 00:00:00.000
2,3,EM,0,NaN,Roberto,NaN,Tamburello,NaN,0,NaN,"<IndividualSurvey xmlns=""http://schemas.micros...",e1a2555e-0828-434b-a33b-6f38136a37de,2007-11-04 00:00:00.000
3,4,EM,0,NaN,Rob,NaN,Walters,NaN,0,NaN,"<IndividualSurvey xmlns=""http://schemas.micros...",f2d7ce06-38b3-4357-805b-f4b6b71c01ff,2007-11-28 00:00:00.000
4,5,EM,0,Ms.,Gail,A,Erickson,NaN,0,NaN,"<IndividualSurvey xmlns=""http://schemas.micros...",f3a3f6b4-ae3b-430c-a754-9f2231ba6fef,2007-12-30 00:00:00.000

============================================================
DATASET: ADDRESS
============================================================

Shape: (19614, 9)

Columns:
['AddressID', 'AddressLine1', 'AddressLine2', 'City', 'StateProvinceID', 'PostalCode', 'SpatialLocation', 'rowguid', 'ModifiedDate']

Data Types:
AddressID          int64
AddressLine1         str
AddressLine2         str
City                 str
StateProvinceID    int64
PostalCode           str
SpatialLocation      str
rowguid              str
ModifiedDate         str
dtype: object

Missing Values:
AddressID              0
AddressLine1           0
AddressLine2       19252
City                   0
StateProvinceID        0
PostalCode             0
SpatialLocation        0
rowguid                0
ModifiedDate           0
dtype: int64

First 5 Rows:

,AddressID,AddressLine1,AddressLine2,City,StateProvinceID,PostalCode,SpatialLocation,rowguid,ModifiedDate
0,1,1970 Napa Ct.,NaN,Bothell,79,98011,0xE6100000010CAE8BFC28BCE4474067A89189898A5EC0,9aadcb0d-36cf-483f-84d8-585c2d4ec6e9,2007-12-04 00:00:00.000
1,2,9833 Mt. Dias Blv.,NaN,Bothell,79,98011,0xE6100000010CD6FA851AE6D74740BC262A0A03905EC0,32a54b9e-e034-4bfb-b573-a71cde60d8c0,2008-11-30 00:00:00.000
2,3,7484 Roundtree Drive,NaN,Bothell,79,98011,0xE6100000010C18E304C4ADE14740DA930C7893915EC0,4c506923-6d1b-452c-a07c-baa6f5b142a4,2013-03-07 00:00:00.000
3,4,9539 Glenside Dr,NaN,Bothell,79,98011,0xE6100000010C813A0D5F9FDE474011A5C28A7C955EC0,e5946c78-4bcc-477f-9fa1-cc09de16a880,2009-02-03 00:00:00.000
4,5,1226 Shoe St.,NaN,Bothell,79,98011,0xE6100000010C61C64D8ABBD94740C460EA3FD8855EC0,fbaff937-4a97-4af0-81fd-b849900e9bb0,2008-12-19 00:00:00.000

============================================================
DATASET: PURCHASE_ORDER_HEADER
============================================================

Shape: (4012, 13)

Columns:
['PurchaseOrderID', 'RevisionNumber', 'Status', 'EmployeeID', 'VendorID', 'ShipMethodID', 'OrderDate', 'ShipDate', 'SubTotal', 'TaxAmt', 'Freight', 'TotalDue', 'ModifiedDate']

Data Types:
PurchaseOrderID      int64
RevisionNumber       int64
Status               int64
EmployeeID           int64
VendorID             int64
ShipMethodID         int64
OrderDate              str
ShipDate               str
SubTotal           float64
TaxAmt             float64
Freight            float64
TotalDue           float64
ModifiedDate           str
dtype: object

Missing Values:
PurchaseOrderID    0
RevisionNumber     0
Status             0
EmployeeID         0
VendorID           0
ShipMethodID       0
OrderDate          0
ShipDate           0
SubTotal           0
TaxAmt             0
Freight            0
TotalDue           0
ModifiedDate       0
dtype: int64

First 5 Rows:

,PurchaseOrderID,RevisionNumber,Status,EmployeeID,VendorID,ShipMethodID,OrderDate,ShipDate,SubTotal,TaxAmt,Freight,TotalDue,ModifiedDate
0,1,4,4,258,1580,3,2011-04-16 00:00:00.000,2011-04-25 00:00:00.000,201.0400,16.0832,5.0260,222.1492,2011-04-25 00:00:00.000
1,2,4,1,254,1496,5,2011-04-16 00:00:00.000,2011-04-25 00:00:00.000,272.1015,21.7681,6.8025,300.6721,2011-04-25 00:00:00.000
2,3,4,4,257,1494,2,2011-04-16 00:00:00.000,2011-04-25 00:00:00.000,8847.3000,707.7840,221.1825,9776.2665,2011-04-25 00:00:00.000
3,4,4,3,261,1650,5,2011-04-16 00:00:00.000,2011-04-25 00:00:00.000,171.0765,13.6861,4.2769,189.0395,2011-04-25 00:00:00.000
4,5,4,4,251,1654,4,2011-04-30 00:00:00.000,2011-05-09 00:00:00.000,20397.3000,1631.7840,509.9325,22539.0165,2011-05-09 00:00:00.000

# Initial Data Understanding

## Objective
The purpose of this section is to build a foundational understanding of the datasets before performing any cleaning or transformation.

This phase focuses on:
- understanding dataset granularity
- identifying key business columns
- recognizing primary and foreign keys
- understanding relationships between tables
- preparing for analytical modeling

---

# Core Business Tables

The project primarily revolves around the sales analytics workflow.

Main relationship pipeline:

Customer
→ Sales Order Header
→ Sales Order Detail
→ Product
→ Product Subcategory
→ Product Category

Regional analysis pipeline:

Sales Territory
→ Sales Order Header

This combined structure forms the foundation for:
- sales analysis
- customer analytics
- product performance analysis
- category-level KPIs
- territory performance analysis
- dashboard reporting

---

# Important Table Granularity

| Table | Granularity |
|---|---|
| sales_order_header | One row per order |
| sales_order_detail | One row per product inside an order |
| customer | One row per customer |
| product | One row per product |
| product_subcategory | One row per product subcategory |
| product_category | One row per product category |
| sales_territory | One row per sales territory |

Understanding granularity is critical before:
- joins
- aggregations
- KPI calculations

---

# Key Relationships

| Parent Table | Child Table | Key |
|---|---|---|
| sales_order_header | sales_order_detail | SalesOrderID |
| customer | sales_order_header | CustomerID |
| product | sales_order_detail | ProductID |
| product_subcategory | product | ProductSubcategoryID |
| product_category | product_subcategory | ProductCategoryID |
| sales_territory | sales_order_header | TerritoryID |

---

# Why This Matters

Understanding relationships helps prevent:
- duplicate aggregations
- incorrect joins
- inflated revenue calculations
- inaccurate KPIs

This phase establishes the analytical foundation required for:
- exploratory analysis
- feature engineering
- dimensional modeling
- SQL analytics
- dashboard development

In [3]:
# =========================================================
# Initial Dataset Understanding
# =========================================================

for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(f"UNDERSTANDING DATASET: {name.upper()}")
    print("=" * 70)

    # Basic Information
    print(f"\nNumber of Rows: {df.shape[0]}")
    print(f"Number of Columns: {df.shape[1]}")

    # Memory Usage
    print("\nMemory Usage:")
    print(df.memory_usage(deep=True).sum() / 1024**2, "MB")

    # Duplicate Rows
    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    # Numerical Summary
    print("\nNumerical Summary:")
    display(df.describe())

    # Categorical Summary
    print("\nCategorical Summary:")
    display(df.describe(include='object'))

======================================================================
UNDERSTANDING DATASET: SALES_ORDER_HEADER
======================================================================

Number of Rows: 31465
Number of Columns: 26

Memory Usage:
21.74037456512451 MB

Duplicate Rows:
0

Numerical Summary:

,SalesOrderID,RevisionNumber,Status,OnlineOrderFlag,CustomerID,SalesPersonID,TerritoryID,BillToAddressID,ShipToAddressID,ShipMethodID,CreditCardID,CurrencyRateID,SubTotal,TaxAmt,Freight,TotalDue,Comment
count,31465.000000,31465.000000,31465.0,31465.000000,31465.000000,3806.000000,31465.000000,31465.000000,31465.000000,31465.000000,30334.000000,13976.000000,31465.000000,31465.000000,31465.000000,31465.000000,0.0
mean,59391.000000,8.000953,5.0,0.879040,20170.175687,280.607987,6.090768,18263.154426,18249.192563,1.483839,9684.100448,9191.499571,3491.065673,323.755743,101.173693,3915.995109,NaN
std,9083.307446,0.030864,0.0,0.326086,6261.728960,4.846965,2.958119,8210.069158,8218.429263,1.304343,5566.299591,2945.170095,11093.452536,1085.054180,339.079427,12515.462713,NaN
min,43659.000000,8.000000,5.0,0.000000,11000.000000,274.000000,1.000000,405.000000,9.000000,1.000000,1.000000,2.000000,1.374000,0.109900,0.034400,1.518300,NaN
25%,51525.000000,8.000000,5.0,1.000000,14432.000000,277.000000,4.000000,14080.000000,14063.000000,1.000000,4894.250000,8510.000000,56.970000,4.557600,1.424300,62.951900,NaN
50%,59391.000000,8.000000,5.0,1.000000,19452.000000,279.000000,6.000000,19449.000000,19438.000000,1.000000,9719.500000,10074.000000,782.990000,62.639200,19.574800,865.204000,NaN
75%,67257.000000,8.000000,5.0,1.000000,25994.000000,284.000000,9.000000,24678.000000,24672.000000,1.000000,14510.750000,11282.000000,2366.960000,189.597600,59.249300,2615.490800,NaN
max,75123.000000,9.000000,5.0,1.000000,30118.000000,290.000000,10.000000,29883.000000,29883.000000,5.000000,19237.000000,12431.000000,163930.394300,17948.518600,5608.912100,187487.825000,NaN

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,OrderDate,DueDate,ShipDate,SalesOrderNumber,PurchaseOrderNumber,AccountNumber,CreditCardApprovalCode,rowguid,ModifiedDate
count,31465,31465,31465,31465,3806,31465,30334,31465,31465
unique,1124,1124,1124,31465,3806,19119,30334,31465,1124
top,2014-03-31 00:00:00.000,2014-04-12 00:00:00.000,2014-04-07 00:00:00.000,SO43659,PO522145787,10-4030-011091,105041Vi84182,79b65321-39ca-4115-9cba-8fe0903e12e6,2014-04-07 00:00:00.000
freq,271,273,273,1,1,28,1,1,273

======================================================================
UNDERSTANDING DATASET: SALES_ORDER_DETAIL
======================================================================

Number of Rows: 121317
Number of Columns: 11

Memory Usage:
30.956253051757812 MB

Duplicate Rows:
0

Numerical Summary:

,SalesOrderID,SalesOrderDetailID,OrderQty,ProductID,SpecialOfferID,UnitPrice,UnitPriceDiscount,LineTotal
count,121317.000000,121317.000000,121317.000000,121317.000000,121317.000000,121317.000000,121317.000000,121317.000000
mean,57827.363782,60659.000000,2.266080,841.680836,1.162541,465.093496,0.002826,905.449207
std,9009.147902,35021.345641,2.491323,86.452124,1.218604,751.885081,0.024811,1693.417389
min,43659.000000,1.000000,1.000000,707.000000,1.000000,1.328200,0.000000,1.374000
25%,49884.000000,30330.000000,1.000000,768.000000,1.000000,21.490000,0.000000,24.990000
50%,57029.000000,60659.000000,1.000000,863.000000,1.000000,49.990000,0.000000,134.982000
75%,65490.000000,90988.000000,3.000000,921.000000,1.000000,602.346000,0.000000,1120.490000
max,75123.000000,121317.000000,44.000000,999.000000,16.000000,3578.270000,0.400000,27893.619000

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,CarrierTrackingNumber,rowguid,ModifiedDate
count,60919,121317,121317
unique,3806,121317,1124
top,9429-430D-89,b207c96d-d9e6-402b-8470-2cc176c42283,2013-06-30 00:00:00.000
freq,72,1,3876

======================================================================
UNDERSTANDING DATASET: CUSTOMER
======================================================================

Number of Rows: 19820
Number of Columns: 7

Memory Usage:
4.687778472900391 MB

Duplicate Rows:
0

Numerical Summary:

         CustomerID      PersonID      StoreID   TerritoryID
count  19820.000000  19119.000000  1336.000000  19820.000000
mean   19844.277094  11184.190230  1037.654940      5.824975
std     6581.785914   5578.705977   475.914755      3.042676
min        1.000000    291.000000   292.000000      1.000000
25%    15253.750000   6438.500000   648.000000      4.000000
50%    20208.500000  11218.000000   993.000000      6.000000
75%    25163.250000  15997.500000  1342.000000      9.000000
max    30118.000000  20777.000000  2051.000000     10.000000

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,AccountNumber,rowguid,ModifiedDate
count,19820,19820,19820
unique,19820,19820,1
top,AW00000001,3f5ae95e-b87d-4aed-95b4-c3797afcb74f,2014-09-12 11:15:07.263
freq,1,1,19820

======================================================================
UNDERSTANDING DATASET: PRODUCT
======================================================================

Number of Rows: 504
Number of Columns: 25

Memory Usage:
0.3728065490722656 MB

Duplicate Rows:
0

Numerical Summary:

,ProductID,MakeFlag,FinishedGoodsFlag,SafetyStockLevel,ReorderPoint,StandardCost,ListPrice,Weight,DaysToManufacture,ProductSubcategoryID,ProductModelID,DiscontinuedDate
count,504.000000,504.000000,504.000000,504.000000,504.000000,504.000000,504.000000,205.000000,504.000000,295.000000,295.000000,0.0
mean,673.039683,0.474206,0.585317,535.150794,401.363095,258.602961,438.666250,74.069220,1.103175,12.294915,37.444068,NaN
std,229.373142,0.499830,0.493157,374.112954,280.584715,461.632808,773.602843,182.166588,1.492616,9.860135,34.025442,NaN
min,1.000000,0.000000,0.000000,4.000000,3.000000,0.000000,0.000000,2.120000,0.000000,1.000000,1.000000,NaN
25%,447.750000,0.000000,0.000000,100.000000,75.000000,0.000000,0.000000,2.880000,0.000000,2.000000,11.000000,NaN
50%,747.500000,0.000000,1.000000,500.000000,375.000000,23.372200,49.990000,17.900000,1.000000,12.000000,26.000000,NaN
75%,873.250000,1.000000,1.000000,1000.000000,750.000000,317.075825,564.990000,27.350000,1.000000,17.000000,48.500000,NaN
max,999.000000,1.000000,1.000000,1000.000000,750.000000,2171.294200,3578.270000,1050.000000,4.000000,37.000000,128.000000,NaN

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,Name,ProductNumber,Color,Size,SizeUnitMeasureCode,WeightUnitMeasureCode,ProductLine,Class,Style,SellStartDate,SellEndDate,rowguid,ModifiedDate
count,504,504,256,211,176,205,278,247,211,504,98,504,504
unique,504,504,9,18,1,2,4,3,3,4,2,504,2
top,Adjustable Race,AR-5381,Black,44,CM,LB,R,L,U,2008-04-30 00:00:00.000,2013-05-29 00:00:00.000,694215b7-08f7-4c0d-acb1-d734ba44c0c8,2014-02-08 10:01:36.827
freq,1,1,93,29,176,176,100,97,176,211,69,1,503

======================================================================
UNDERSTANDING DATASET: PRODUCT_CATEGORY
======================================================================

Number of Rows: 4
Number of Columns: 4

Memory Usage:
0.0009746551513671875 MB

Duplicate Rows:
0

Numerical Summary:

       ProductCategoryID
count           4.000000
mean            2.500000
std             1.290994
min             1.000000
25%             1.750000
50%             2.500000
75%             3.250000
max             4.000000

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

         Name                               rowguid             ModifiedDate
count       4                                     4                        4
unique      4                                     4                        1
top     Bikes  cfbda25c-df71-47a7-b81b-64ee161aa37c  2008-04-30 00:00:00.000
freq        1                                     1                        4

======================================================================
UNDERSTANDING DATASET: PRODUCT_SUBCATEGORY
======================================================================

Number of Rows: 37
Number of Columns: 5

Memory Usage:
0.008273124694824219 MB

Duplicate Rows:
0

Numerical Summary:

       ProductSubcategoryID  ProductCategoryID
count             37.000000          37.000000
mean              19.000000           2.783784
std               10.824355           1.003747
min                1.000000           1.000000
25%               10.000000           2.000000
50%               19.000000           3.000000
75%               28.000000           4.000000
max               37.000000           4.000000

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,Name,rowguid,ModifiedDate
count,37,37,37
unique,37,37,1
top,Mountain Bikes,2d364ade-264a-433c-b092-4fcbf3804e01,2008-04-30 00:00:00.000
freq,1,1,37

======================================================================
UNDERSTANDING DATASET: SALES_TERRITORY
======================================================================

Number of Rows: 10
Number of Columns: 10

Memory Usage:
0.003604888916015625 MB

Duplicate Rows:
0

Numerical Summary:

       TerritoryID      SalesYTD  SalesLastYear  CostYTD  CostLastYear
count     10.00000  1.000000e+01   1.000000e+01     10.0          10.0
mean       5.50000  5.275121e+06   3.271536e+06      0.0           0.0
std        3.02765  2.582996e+06   1.456222e+06      0.0           0.0
min        1.00000  2.402177e+06   1.307950e+06      0.0           0.0
25%        3.25000  3.255432e+06   2.308047e+06      0.0           0.0
50%        5.50000  4.892652e+06   3.251854e+06      0.0           0.0
75%        7.75000  6.573326e+06   3.845591e+06      0.0           0.0
max       10.00000  1.051085e+07   5.693989e+06      0.0           0.0

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,Name,CountryRegionCode,Group,rowguid,ModifiedDate
count,10,10,10,10,10
unique,10,6,3,10,1
top,Northwest,US,North America,43689a10-e30b-497f-b0de-11de20267ff7,2008-04-30 00:00:00.000
freq,1,5,6,1,10

======================================================================
UNDERSTANDING DATASET: SALES_PERSON
======================================================================

Number of Rows: 17
Number of Columns: 9

Memory Usage:
0.0035791397094726562 MB

Duplicate Rows:
0

Numerical Summary:

,BusinessEntityID,TerritoryID,SalesQuota,Bonus,CommissionPct,SalesYTD,SalesLastYear
count,17.000000,14.000000,14.000000,17.000000,17.000000,1.700000e+01,1.700000e+01
mean,282.000000,4.785714,260714.285714,2859.411765,0.011765,2.133976e+06,1.393292e+06
std,5.049752,3.017349,21290.765681,2273.314542,0.006495,1.243721e+06,8.492445e+05
min,274.000000,1.000000,250000.000000,0.000000,0.000000,1.725245e+05,0.000000e+00
25%,278.000000,2.250000,250000.000000,500.000000,0.010000,1.421811e+06,1.307950e+06
50%,282.000000,4.500000,250000.000000,3500.000000,0.012000,1.827067e+06,1.635823e+06
75%,286.000000,6.750000,250000.000000,5000.000000,0.016000,3.121616e+06,1.997186e+06
max,290.000000,10.000000,300000.000000,6700.000000,0.020000,4.251369e+06,2.396540e+06

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

                                     rowguid             ModifiedDate
count                                     17                       17
unique                                    17                        7
top     48754992-9ee0-4c0e-8c94-9451604e3e02  2011-05-24 00:00:00.000
freq                                       1                        9

======================================================================
UNDERSTANDING DATASET: PERSON
======================================================================

Number of Rows: 19972
Number of Columns: 13

Memory Usage:
20.990745544433594 MB

Duplicate Rows:
0

Numerical Summary:

       BusinessEntityID  NameStyle  EmailPromotion
count      19972.000000    19972.0    19972.000000
mean       10763.079411        0.0        0.630082
std         5814.133272        0.0        0.781433
min            1.000000        0.0        0.000000
25%         5798.750000        0.0        0.000000
50%        10791.500000        0.0        0.000000
75%        15784.250000        0.0        1.000000
max        20777.000000        0.0        2.000000

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,PersonType,Title,FirstName,MiddleName,LastName,Suffix,AdditionalContactInfo,Demographics,rowguid,ModifiedDate
count,19972,1009,19972,11473,19972,53,10,19972,19972,19972
unique,6,6,1018,71,1206,6,10,19114,19972,1285
top,IN,Mr.,Richard,A,Diaz,Jr.,"<AdditionalContactInfo xmlns=""http://schemas.m...","<IndividualSurvey xmlns=""http://schemas.micros...",92c4279f-1207-48a3-8448-4636514eb7e2,2013-07-31 00:00:00.000
freq,18484,577,103,1319,211,33,1,853,1,136

======================================================================
UNDERSTANDING DATASET: ADDRESS
======================================================================

Number of Rows: 19614
Number of Columns: 9

Memory Usage:
8.968647003173828 MB

Duplicate Rows:
0

Numerical Summary:

          AddressID  StateProvinceID
count  19614.000000     19614.000000
mean   19516.281228        49.284644
std     6961.696423        46.108624
min        1.000000         1.000000
25%    15190.250000         9.000000
50%    20093.500000        50.000000
75%    24996.750000        77.000000
max    32521.000000       181.000000

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,AddressLine1,AddressLine2,City,PostalCode,SpatialLocation,rowguid,ModifiedDate
count,19614,362,19614,19614,19614,19614,19614
unique,13572,195,575,661,17878,19614,1280
top,Attaché de Presse,Verkaufsabteilung,London,98168,0xE6100000010C00000000000000000000000000000000,9aadcb0d-36cf-483f-84d8-585c2d4ec6e9,2013-12-21 10:09:29.423
freq,17,35,434,215,918,1,1851

======================================================================
UNDERSTANDING DATASET: PURCHASE_ORDER_HEADER
======================================================================

Number of Rows: 4012
Number of Columns: 13

Memory Usage:
1.1326637268066406 MB

Duplicate Rows:
0

Numerical Summary:

,PurchaseOrderID,RevisionNumber,Status,EmployeeID,VendorID,ShipMethodID,SubTotal,TaxAmt,Freight,TotalDue
count,4012.000000,4012.000000,4012.000000,4012.000000,4012.000000,4012.000000,4012.000000,4012.000000,4012.000000,4.012000e+03
mean,2006.500000,4.083001,3.804337,255.977567,1598.033898,3.572782,15900.297816,1272.023822,394.810126,1.756713e+04
std,1158.308969,0.502638,0.707090,3.299856,61.020858,1.487230,28142.440320,2251.395227,644.049520,3.103399e+04
min,1.000000,4.000000,1.000000,250.000000,1492.000000,1.000000,37.075500,2.966000,0.926900,4.096840e+01
25%,1003.750000,4.000000,4.000000,253.000000,1544.000000,2.000000,389.655000,31.172400,9.741400,4.305688e+02
50%,2006.500000,4.000000,4.000000,256.000000,1600.000000,4.000000,2934.540000,234.763200,73.363500,3.242667e+03
75%,3009.250000,4.000000,4.000000,259.000000,1652.000000,5.000000,28199.325000,2255.946000,704.983100,3.116025e+04
max,4012.000000,20.000000,4.000000,261.000000,1698.000000,5.000000,997680.000000,79814.400000,19953.600000,1.097448e+06

Categorical Summary:

/var/folders/qz/809bk0757sz958kkr3n0_v9h0000gn/T/ipykernel_99680/979396014.py:29: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,OrderDate,ShipDate,ModifiedDate
count,4012,4012,4012
unique,300,297,306
top,2013-08-13 00:00:00.000,2013-08-22 00:00:00.000,2013-08-22 00:00:00.000
freq,20,20,20